# Customizing the Toggle Key By default, espanso can be temporarily disabled and enabled by pressing the Alt key twice, resulting in a notification saying “espanso disabled.” Pressing Alt twice again will enable it, and you’ll receive a notification saying “espanso enabled.” If you’d like to customize the key, simply add the toggle_key option to your default.yml configuration and set it to one of the available options:

toggle_key: OFF

# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"



  # C:\Users\ashraaf\AppData\Roaming\espanso
  # custom text replacements
  - trigger: "ސ-"
    replace: "ﷺ"

  - trigger: "s-"
    replace: "ﷺ"

  - trigger: "\"-"
    replace: "”"

  - trigger: "-\""
    replace: "“"

  - trigger: "\'-"
    replace: "’"

  - trigger: "\'-"
    replace: "‘"

  - trigger: "br-"
    replace: "<br><br>"

  - trigger: "ބރ-"
    replace: "<br><br>"

  - trigger: "ރއ-"
    replace: "رَضِيَ اللَّهُ عَنْهُ"

  - trigger: "ރހ-"
    replace: "رَضِيَ اللَّهُ عَنْهَا"

  - trigger: "ރމ2-"
    replace: "رَضِيَ اللَّهُ عَنْهُمَا"

  - trigger: "ރމ-"
    replace: "رَضِيَ اللَّهُ عَنْهُمْ"

  - trigger: "ރވ-"
    replace: "ރިވާ ކުރެއްވިއެވެ:"

  - trigger: "ރހކ-"
    replace: "ރަސޫލު ﷲ ﷺ ޙަދީޘް ކުރެއްވިއެވެ:"

  - trigger: "ނހކ-"
    replace: "ނަބިއްޔާ ﷺ ޙަދީޘް ކުރެއްވިއެވެ:"

  - trigger: "ރއޑ-"
    replace: "ރަސޫލު ﷲ ﷺ ޙަދީޘް ކުރައްވަނިކޮށް ތިމަން އަޑު އެހީމެވެ:"

  - trigger: "ޞ-"
    replace: "މި ޙަދީޘް ޞައްޙަ ކުރެއްވިއެވެ."

  - trigger: "ޟ-"
    replace: "މި ޙަދީޘް ޟަޢީފު ކުރެއްވިއެވެ."

  - trigger: "މރވ-"
    replace: "މި ޙަދީޘް ރިވާ ކުރެއްވީ"

  - trigger: "salam-"
    replace: "السلام عليكم ورحمة الله وبركاته"

  - trigger: "wsalam-"
    replace: "وعليكم السلام ورحمة الله وبركاته"

  - trigger: "hamd-"
    replace: "الحمد لله"

  - trigger: "keyf-"
    replace: "كيف حالك"

  - trigger: "jazak-"
    replace: "جزاك الله خيرا"

  - trigger: "barak-"
    replace: "بارك الله فيك"

  - trigger: "pr-"
    replace: "present"

  - trigger: "thk-"
    replace: "thank you"
    
  - trigger: "wc-"
    replace: "welcome"
    
  - trigger: "gn-"
    replace: "good night"
    
  - trigger: "tc-"
    replace: "take care"
    
    
    
    
    