# Customizing the Toggle Key By default, espanso can be temporarily disabled and enabled by pressing the Alt key twice, resulting in a notification saying “espanso disabled.” Pressing Alt twice again will enable it, and you’ll receive a notification saying “espanso enabled.” If you’d like to customize the key, simply add the toggle_key option to your default.yml configuration and set it to one of the available options:

toggle_key: OFF

# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"



  # C:\Users\ashraaf\AppData\Roaming\espanso
  # custom text replacements
  - trigger: "ސސ-"
    replace: "ﷺ"

  - trigger: "ss-"
    replace: "ﷺ"

  - trigger: "صص-"
    replace: "ﷺ"

  - trigger: "\"-"
    replace: "”"

  - trigger: "-\""
    replace: "“"

  - trigger: "\'-"
    replace: "’"

  - trigger: "-\'"
    replace: "‘"

  - trigger: "رض-"
    replace: "رَضِيَ اللَّهُ عَنْهُ"

  - trigger: "ރއ-"
    replace: "رَضِيَ اللَّهُ عَنْهُ"

  - trigger: "ra-"
    replace: "رَضِيَ اللَّهُ عَنْهُ"

  - trigger: "رض-"
    replace: "رَضِيَ اللَّهُ عَنْهَا"

  - trigger: "ރއހ-"
    replace: "رَضِيَ اللَّهُ عَنْهَا"

  - trigger: "rah-"
    replace: "رَضِيَ اللَّهُ عَنْهَا"

  - trigger: "رض2-"
    replace: "رَضِيَ اللَّهُ عَنْهُمَا"

  - trigger: "ރއ2-"
    replace: "رَضِيَ اللَّهُ عَنْهُمَا"

  - trigger: "ra2-"
    replace: "رَضِيَ اللَّهُ عَنْهُمَا"

  - trigger: "رض3-"
    replace: "رَضِيَ اللَّهُ عَنْهُمْ"

  - trigger: "ރއ3-"
    replace: "رَضِيَ اللَّهُ عَنْهُمْ"

  - trigger: "ra3-"
    replace: "رَضِيَ اللَّهُ عَنْهُمْ"

  - trigger: "ވދ-"
    replace: "ވިދާޅުވިއެވެ: "

  - trigger: "ދނ-"
    replace: "ދެންނެވިއެވެ: "

  - trigger: "ރވ-"
    replace: "ރިވާވެގެންވެއެވެ: "

  - trigger: "ރކ-"
    replace: "ރިވާ ކުރެއްވީ"

  - trigger: "ރކއ-"
    replace: "ރިވާ ކުރެއްވިއެވެ :"

  - trigger: "ނރ-"
    replace: "ނެރުއްވީ"

  - trigger: "މހ-"
    replace: "މި ޙަދީޘް"

  - trigger: "ވރ-"
    replace: "ވިދާޅުވިކަމަށް ރިވާވެގެންވެއެވެ: "

  - trigger: "ގރ-"
    replace: "ގެ އަރިހުން ރިވާވެގެންވެއެވެ: "

  - trigger: "އއރ-"
    replace: "އަދި އެހެން ރިވާޔަތެއްގައި ވެއެވެ: "

  - trigger: "ރހކ-"
    replace: "ރަސޫލު ﷲ ﷺ ޙަދީޘް ކުރެއްވިއެވެ: ”"

  - trigger: "ނހކ-"
    replace: "ނަބިއްޔާ ﷺ ޙަދީޘް ކުރެއްވިއެވެ: ”"

  # ހކ should only come after the previous two, otherwise might override them in js, even if not in espanso

  - trigger: "ހކ-"
    replace: "ޙަދީޘް ކުރެއްވިއެވެ: ”"
    
  - trigger: "ހމ-"
    replace: "ހަމަކަށަވަރުން"

  - trigger: "އކ-"
    replace: "އެކަލޭގެފާނު"

  - trigger: "ކލ-"
    replace: "ކަލޭގެފާނު"
    
  - trigger: "ހދ-"
    replace: "ޙަދީޘް"

  - trigger: "ރސ-"
    replace: "ރަސޫލު ﷲ ﷺ"

  - trigger: "ނސ-"
    replace: "ނަބިއްޔާ ﷺ"

  - trigger: "ރއޑ-"
    replace: "ރަސޫލު ﷲ ﷺ ޙަދީޘް ކުރައްވަނިކޮށް ތިމަން އަޑު އެހީމެވެ: ”"
    
  - trigger: "ނއޑ-"
    replace: "ނަބިއްޔާ ﷺ ޙަދީޘް ކުރައްވަނިކޮށް ތިމަން އަޑު އެހީމެވެ: ”"

  - trigger: "ސައްހަ-"
    replace: "މި ޙަދީޘް ސައްހަ ކުރެއްވިއެވެ."

  - trigger: "ޟ-"
    replace: "މި ޙަދީޘް ޟަޢީފު ކުރެއްވިއެވެ."

  - trigger: "މރވ-"
    replace: "މި ޙަދީޘް ރިވާ ކުރެއްވީ"

  - trigger: "salam-"
    replace: "السلام عليكم ورحمة الله وبركاته"

  - trigger: "wsalam-"
    replace: "وعليكم السلام ورحمة الله وبركاته"

  - trigger: "hamd-"
    replace: "الحمد لله"

  - trigger: "keyf-"
    replace: "كيف حالك"

  - trigger: "jazak-"
    replace: "جزاك الله خيرا"

  - trigger: "barak-"
    replace: "بارك الله فيك"

  - trigger: "bismi-"
    replace: "بسم الله الرحمن الرحيم"
    
  - trigger: "pr-"
    replace: "present"

  - trigger: "thk-"
    replace: "thank you"
    
  - trigger: "wc-"
    replace: "welcome"
    
  - trigger: "gn-"
    replace: "good night"
    
  - trigger: "tc-"
    replace: "take care"

  - trigger: "cc-"
    replace: "git commit -a -m \"u\""

  - trigger: "pp-"
    replace: "git push"

    
    