name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ github.actor }}
          url: https://gitlab.com/${{ github.repository }}.git
          # Personal access token from gitlab.com 
          token: ${{ secrets.MIRROR_TRY_ME_TOKEN }}
