name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/hadithmv/hadithmv.github.io"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "hadithmv"
        GITLAB_PASSWORD: ${{ secrets.MIRROR_TRY_ME_TOKEN }}
        GITLAB_PROJECT_ID: "https://gitlab.com/hadithmv/hadithmv.github.io/edit"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
