# https://github.com/wearerequired/git-mirror-action

name: Mirror to Bitbucket Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          # secrets.SSH_PRIVATE_KEY
          # SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          # commented out above, and added below
          GIT_SSH_NO_VERIFY_HOST: "true"
        with:
          source-repo: "git@github.com:hadithmv/hadithmv.github.io.git"
          destination-repo: "git@bitbucket.org:hadithmv/hadithmv.github.io.git"
