name: Mirror example
on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --mirror https://github.com/hadithmv/hadithmv.github.io .
      - run: git push --mirror "https://gitlab.com/hadithmv/hadithmv.github.io.git"
        env:
          TOKEN: ${{ secrets.MIRROR_TRY_ME_TOKEN }}
